app = 'crowdpad-server'
primary_region = 'lax'

[build]

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[services]]
protocol = 'tcp'
internal_port = 8080

[[services.ports]]
port = 80
handlers = ['http']

[[services.ports]]
port = 443
handlers = ['tls', 'http']

[services.concurrency]
hard_limit = 200
soft_limit = 150

[[services.tcp_checks]]
interval = '10s'
timeout = '2s'

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
