name: Deploy `server`
on:
  push:
    branches:
      - master
    paths:
      - 'server/**'
      - '.github/workflows/server-deploy.yaml'

concurrency:
  group: 'server-deploy'
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: server-production
      url: https://crowdpad-server.fly.dev/health
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: server/
          sparse-checkout-cone-mode: true

      - name: Set up flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy using flyctl
        run: flyctl deploy --remote-only
        working-directory: ./server
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
